//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnesInstaller.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnesInstaller.Strings.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string About_CloseButton {
            get {
                return ResourceManager.GetString("About_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnesInstaller v{1}{0}{0}MIT License{0}{0}Copyright (c) 2018 {5}{0}{0}Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:{0}{0}The a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string Home_AboutButton {
            get {
                return ResourceManager.GetString("Home_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game progress....
        /// </summary>
        internal static string Home_ExportButton {
            get {
                return ResourceManager.GetString("Home_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a path to save game progress file....
        /// </summary>
        internal static string Home_ExportChooserTitle {
            get {
                return ResourceManager.GetString("Home_ExportChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t export game progress successfully! Try again..
        /// </summary>
        internal static string Home_ExportError {
            get {
                return ResourceManager.GetString("Home_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game Progress.
        /// </summary>
        internal static string Home_ExportErrorTitle {
            get {
                return ResourceManager.GetString("Home_ExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game progress exported successfully!.
        /// </summary>
        internal static string Home_ExportSuccess {
            get {
                return ResourceManager.GetString("Home_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game Progress.
        /// </summary>
        internal static string Home_ExportSuccessTitle {
            get {
                return ResourceManager.GetString("Home_ExportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download new games from trusted sources on the internet. Then, add the binary files of these in this directory..
        /// </summary>
        internal static string Home_GamesAlert {
            get {
                return ResourceManager.GetString("Home_GamesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Games.
        /// </summary>
        internal static string Home_GamesAlertTitle {
            get {
                return ResourceManager.GetString("Home_GamesAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Games.
        /// </summary>
        internal static string Home_GamesButton {
            get {
                return ResourceManager.GetString("Home_GamesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: you may lose currently saved games progress if you used the same name to save them..
        /// </summary>
        internal static string Home_ImportAlert {
            get {
                return ResourceManager.GetString("Home_ImportAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Progress.
        /// </summary>
        internal static string Home_ImportAlertTitle {
            get {
                return ResourceManager.GetString("Home_ImportAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game progress....
        /// </summary>
        internal static string Home_ImportButton {
            get {
                return ResourceManager.GetString("Home_ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previously saved game progress file....
        /// </summary>
        internal static string Home_ImportChooserTitle {
            get {
                return ResourceManager.GetString("Home_ImportChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t import game progress successfully! Try again..
        /// </summary>
        internal static string Home_ImportError {
            get {
                return ResourceManager.GetString("Home_ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game Progress.
        /// </summary>
        internal static string Home_ImportErrorTitle {
            get {
                return ResourceManager.GetString("Home_ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game progress imported successfully!.
        /// </summary>
        internal static string Home_ImportSuccess {
            get {
                return ResourceManager.GetString("Home_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game Progress.
        /// </summary>
        internal static string Home_ImportSuccessTitle {
            get {
                return ResourceManager.GetString("Home_ImportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Home_PlayButton {
            get {
                return ResourceManager.GetString("Home_PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall....
        /// </summary>
        internal static string Home_ReinstallButton {
            get {
                return ResourceManager.GetString("Home_ReinstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        internal static string Home_ScreenshotsButton {
            get {
                return ResourceManager.GetString("Home_ScreenshotsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t start the application! Try to reinstall it..
        /// </summary>
        internal static string Home_StartError {
            get {
                return ResourceManager.GetString("Home_StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Home_StartErrorTitle {
            get {
                return ResourceManager.GetString("Home_StartErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is not properly installed! Try to reinstall it..
        /// </summary>
        internal static string Home_StartNotFound {
            get {
                return ResourceManager.GetString("Home_StartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Home_StartNotFoundTitle {
            get {
                return ResourceManager.GetString("Home_StartNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall....
        /// </summary>
        internal static string Home_UninstallButton {
            get {
                return ResourceManager.GetString("Home_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the installed application and all its content? You may lose everything you&apos;ve done..
        /// </summary>
        internal static string Home_UninstallConfirm {
            get {
                return ResourceManager.GetString("Home_UninstallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Home_UninstallConfirmTitle {
            get {
                return ResourceManager.GetString("Home_UninstallConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t uninstall successfully! Try again..
        /// </summary>
        internal static string Home_UninstallError {
            get {
                return ResourceManager.GetString("Home_UninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation.
        /// </summary>
        internal static string Home_UninstallErrorTitle {
            get {
                return ResourceManager.GetString("Home_UninstallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uninstalled!.
        /// </summary>
        internal static string Home_UninstallSuccess {
            get {
                return ResourceManager.GetString("Home_UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation.
        /// </summary>
        internal static string Home_UninstallSuccessTitle {
            get {
                return ResourceManager.GetString("Home_UninstallSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and Close.
        /// </summary>
        internal static string Install_ButtonClose {
            get {
                return ResourceManager.GetString("Install_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install_ButtonConfirm {
            get {
                return ResourceManager.GetString("Install_ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a shortcut icon on my Desktop Folder..
        /// </summary>
        internal static string Install_DesktopFieldText {
            get {
                return ResourceManager.GetString("Install_DesktopFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t install successfully! Try again..
        /// </summary>
        internal static string Install_Error {
            get {
                return ResourceManager.GetString("Install_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        internal static string Install_ErrorTitle {
            get {
                return ResourceManager.GetString("Install_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will guide you through the installation of Shiginima Minecraft Launcher..
        /// </summary>
        internal static string Install_Info {
            get {
                return ResourceManager.GetString("Install_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Install_Lang {
            get {
                return ResourceManager.GetString("Install_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed!.
        /// </summary>
        internal static string Install_Success {
            get {
                return ResourceManager.GetString("Install_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        internal static string Install_SuccessTitle {
            get {
                return ResourceManager.GetString("Install_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a moment....
        /// </summary>
        internal static string Process_Text {
            get {
                return ResourceManager.GetString("Process_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mandatory update. You will not be able to start the program until you update..
        /// </summary>
        internal static string Splash_RequiredUpdateCancelled {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Update.
        /// </summary>
        internal static string Splash_RequiredUpdateCancelledTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a mandatory update available, and you will not be able to start the program until you update.{0}{0}Download the update for the program on the website:{0}{1}.
        /// </summary>
        internal static string Splash_RequiredUpdateDownload {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a mandatory update available, and you will not be able to start the program until you update. The update has been automatically downloaded and will now be applied. You must manually continue the installation..
        /// </summary>
        internal static string Splash_RequiredUpdateDownloaded {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Update.
        /// </summary>
        internal static string Splash_RequiredUpdateDownloadedTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Update.
        /// </summary>
        internal static string Splash_RequiredUpdateDownloadTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a mandatory update available, and you will not be able to start the program until you update.{0}{0}Download the update for the program on the website:{0}{1}.
        /// </summary>
        internal static string Splash_RequiredUpdateError {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Update.
        /// </summary>
        internal static string Splash_RequiredUpdateErrorTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available for the program, and you can update at any time.{0}{0}Download the update for the program on the website:{0}{1}.
        /// </summary>
        internal static string Splash_UpdateDownload {
            get {
                return ResourceManager.GetString("Splash_UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Splash_UpdateDownloadTitle {
            get {
                return ResourceManager.GetString("Splash_UpdateDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the update for the program on the website:{0}{1}.
        /// </summary>
        internal static string Splash_UpdateError {
            get {
                return ResourceManager.GetString("Splash_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Splash_UpdateErrorTitle {
            get {
                return ResourceManager.GetString("Splash_UpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available for the program, and you can update at any time.{0}Do you want to update now?.
        /// </summary>
        internal static string Splash_UpdateQuestion {
            get {
                return ResourceManager.GetString("Splash_UpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Splash_UpdateQuestionTitle {
            get {
                return ResourceManager.GetString("Splash_UpdateQuestionTitle", resourceCulture);
            }
        }
    }
}
