//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnesInstaller.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnesInstaller.Strings.pt", typeof(pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string About_CloseButton {
            get {
                return ResourceManager.GetString("About_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string About_Text_ {
            get {
                return ResourceManager.GetString("About_Text_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre....
        /// </summary>
        internal static string Home_AboutButton {
            get {
                return ResourceManager.GetString("Home_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar progresso de jogo....
        /// </summary>
        internal static string Home_ExportButton {
            get {
                return ResourceManager.GetString("Home_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o local de salvamento do arquivo....
        /// </summary>
        internal static string Home_ExportChooserTitle {
            get {
                return ResourceManager.GetString("Home_ExportChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao exportar progresso de jogo! Tente novamente..
        /// </summary>
        internal static string Home_ExportError {
            get {
                return ResourceManager.GetString("Home_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Progresso de Jogo.
        /// </summary>
        internal static string Home_ExportErrorTitle {
            get {
                return ResourceManager.GetString("Home_ExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progresso de jogo exportado com sucesso!.
        /// </summary>
        internal static string Home_ExportSuccess {
            get {
                return ResourceManager.GetString("Home_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Progresso de Jogo.
        /// </summary>
        internal static string Home_ExportSuccessTitle {
            get {
                return ResourceManager.GetString("Home_ExportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você pode baixar novos jogos de fontes confiáveis da internet. Depois, adicione os arquivos binários destes jogos neste diretório..
        /// </summary>
        internal static string Home_GamesAlert {
            get {
                return ResourceManager.GetString("Home_GamesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogos Instalados.
        /// </summary>
        internal static string Home_GamesAlertTitle {
            get {
                return ResourceManager.GetString("Home_GamesAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogos Instalados.
        /// </summary>
        internal static string Home_GamesButton {
            get {
                return ResourceManager.GetString("Home_GamesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção: você pode perder jogos salvos no momento se você usou o mesmo nome para salvá-los..
        /// </summary>
        internal static string Home_ImportAlert {
            get {
                return ResourceManager.GetString("Home_ImportAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Progresso de Jogo.
        /// </summary>
        internal static string Home_ImportAlertTitle {
            get {
                return ResourceManager.GetString("Home_ImportAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar progresso de jogo....
        /// </summary>
        internal static string Home_ImportButton {
            get {
                return ResourceManager.GetString("Home_ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o arquivo previamente salvo....
        /// </summary>
        internal static string Home_ImportChooserTitle {
            get {
                return ResourceManager.GetString("Home_ImportChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao importar progresso de jogo! Tente novamente..
        /// </summary>
        internal static string Home_ImportError {
            get {
                return ResourceManager.GetString("Home_ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Progresso de Jogo.
        /// </summary>
        internal static string Home_ImportErrorTitle {
            get {
                return ResourceManager.GetString("Home_ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progresso de jogo importado com sucesso!.
        /// </summary>
        internal static string Home_ImportSuccess {
            get {
                return ResourceManager.GetString("Home_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Progresso de Jogo.
        /// </summary>
        internal static string Home_ImportSuccessTitle {
            get {
                return ResourceManager.GetString("Home_ImportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogar.
        /// </summary>
        internal static string Home_PlayButton {
            get {
                return ResourceManager.GetString("Home_PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstalar....
        /// </summary>
        internal static string Home_ReinstallButton {
            get {
                return ResourceManager.GetString("Home_ReinstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturas de Tela.
        /// </summary>
        internal static string Home_ScreenshotsButton {
            get {
                return ResourceManager.GetString("Home_ScreenshotsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível iniciar o aplicativo! Tente instalar ele novamente (reinstalar)..
        /// </summary>
        internal static string Home_StartError {
            get {
                return ResourceManager.GetString("Home_StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string Home_StartErrorTitle {
            get {
                return ResourceManager.GetString("Home_StartErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplicativo não está corretamente instalado! Tente instalar ele novamente (reinstalar)..
        /// </summary>
        internal static string Home_StartNotFound {
            get {
                return ResourceManager.GetString("Home_StartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string Home_StartNotFoundTitle {
            get {
                return ResourceManager.GetString("Home_StartNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar....
        /// </summary>
        internal static string Home_UninstallButton {
            get {
                return ResourceManager.GetString("Home_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja remover o aplicativo instalado e todo o ser conteúdo? Você vai perder tudo o que já fez..
        /// </summary>
        internal static string Home_UninstallConfirm {
            get {
                return ResourceManager.GetString("Home_UninstallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar.
        /// </summary>
        internal static string Home_UninstallConfirmTitle {
            get {
                return ResourceManager.GetString("Home_UninstallConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao desinstalar! Tente novamente..
        /// </summary>
        internal static string Home_UninstallError {
            get {
                return ResourceManager.GetString("Home_UninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalação.
        /// </summary>
        internal static string Home_UninstallErrorTitle {
            get {
                return ResourceManager.GetString("Home_UninstallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalado com sucesso!.
        /// </summary>
        internal static string Home_UninstallSuccess {
            get {
                return ResourceManager.GetString("Home_UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalação.
        /// </summary>
        internal static string Home_UninstallSuccessTitle {
            get {
                return ResourceManager.GetString("Home_UninstallSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar e Fechar.
        /// </summary>
        internal static string Install_ButtonClose {
            get {
                return ResourceManager.GetString("Install_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar.
        /// </summary>
        internal static string Install_ButtonConfirm {
            get {
                return ResourceManager.GetString("Install_ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar ícone de atalho na Área de Trabalho..
        /// </summary>
        internal static string Install_DesktopFieldText {
            get {
                return ResourceManager.GetString("Install_DesktopFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao instalar! Tente novamente..
        /// </summary>
        internal static string Install_Error {
            get {
                return ResourceManager.GetString("Install_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalação.
        /// </summary>
        internal static string Install_ErrorTitle {
            get {
                return ResourceManager.GetString("Install_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vamos prosseguir com a instalação do Snes..
        /// </summary>
        internal static string Install_Info {
            get {
                return ResourceManager.GetString("Install_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        internal static string Install_Lang {
            get {
                return ResourceManager.GetString("Install_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalado com sucesso!.
        /// </summary>
        internal static string Install_Success {
            get {
                return ResourceManager.GetString("Install_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalação.
        /// </summary>
        internal static string Install_SuccessTitle {
            get {
                return ResourceManager.GetString("Install_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde um momento....
        /// </summary>
        internal static string Process_Text {
            get {
                return ResourceManager.GetString("Process_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É uma atualização obrigatória. Você não vai poder iniciar o programa enquanto não atualizar..
        /// </summary>
        internal static string Splash_RequiredUpdateCancelled {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização Obrigatória.
        /// </summary>
        internal static string Splash_RequiredUpdateCancelledTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há uma atualização obrigatória disponível, e você não poderá utilizar o programa enquanto não atualizar.{0}{0}Baixe a nova versão do programa no website:{0}{1}.
        /// </summary>
        internal static string Splash_RequiredUpdateDownload {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há uma atualização obrigatória disponível, e você não poderá utilizar o programa enquanto não atualizar. A atualização foi automaticamente baixada e será aplicada agora. Você deve continuar a instalação manualmente..
        /// </summary>
        internal static string Splash_RequiredUpdateDownloaded {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização Obrigatória.
        /// </summary>
        internal static string Splash_RequiredUpdateDownloadedTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização Obrigatória.
        /// </summary>
        internal static string Splash_RequiredUpdateDownloadTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há uma atualização obrigatória disponível, e você não poderá utilizar o programa enquanto não atualizar.{0}{0}Baixe a nova versão do programa no website:{0}{1}.
        /// </summary>
        internal static string Splash_RequiredUpdateError {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização Obrigatória.
        /// </summary>
        internal static string Splash_RequiredUpdateErrorTitle {
            get {
                return ResourceManager.GetString("Splash_RequiredUpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há uma atualização disponível para o programa, e você pode atualizar a qualquer momento.{0}{0}Baixe a nova versão do programa no website:{0}{1}.
        /// </summary>
        internal static string Splash_UpdateDownload {
            get {
                return ResourceManager.GetString("Splash_UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização.
        /// </summary>
        internal static string Splash_UpdateDownloadTitle {
            get {
                return ResourceManager.GetString("Splash_UpdateDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixe a nova versão do programa no website:{0}{1}.
        /// </summary>
        internal static string Splash_UpdateError {
            get {
                return ResourceManager.GetString("Splash_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização.
        /// </summary>
        internal static string Splash_UpdateErrorTitle {
            get {
                return ResourceManager.GetString("Splash_UpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há uma atualização disponível para o programa, e você pode atualizar a qualquer momento.{0}Deseja atualizar agora?.
        /// </summary>
        internal static string Splash_UpdateQuestion {
            get {
                return ResourceManager.GetString("Splash_UpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização.
        /// </summary>
        internal static string Splash_UpdateQuestionTitle {
            get {
                return ResourceManager.GetString("Splash_UpdateQuestionTitle", resourceCulture);
            }
        }
    }
}
